/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as VocabRouteImport } from './routes/vocab'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnPinyinRouteImport } from './routes/learn.pinyin'
import { Route as LearnPracticeRouteImport } from './routes/learn.practice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabRoute = VocabRouteImport.update({
  id: '/vocab',
  path: '/vocab',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const LearnPinyinRoute = LearnPinyinRouteImport.update({
  id: '/pinyin',
  path: '/pinyin',
  getParentRoute: () => LearnRoute,
} as any)
const LearnPracticeRoute = LearnPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => LearnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn': typeof LearnRouteWithChildren
  '/profile': typeof ProfileRoute
  '/vocab': typeof VocabRoute
  '/learn/pinyin': typeof LearnPinyinRoute
  '/learn/practice': typeof LearnPracticeRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/vocab': typeof VocabRoute
  '/learn/pinyin': typeof LearnPinyinRoute
  '/learn/practice': typeof LearnPracticeRoute
  '/learn': typeof LearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn': typeof LearnRouteWithChildren
  '/profile': typeof ProfileRoute
  '/vocab': typeof VocabRoute
  '/learn/pinyin': typeof LearnPinyinRoute
  '/learn/practice': typeof LearnPracticeRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/learn'
    | '/profile'
    | '/vocab'
    | '/learn/pinyin'
    | '/learn/practice'
    | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/profile' | '/vocab' | '/learn/pinyin' | '/learn/practice' | '/learn'
  id:
    | '__root__'
    | '/'
    | '/learn'
    | '/profile'
    | '/vocab'
    | '/learn/pinyin'
    | '/learn/practice'
    | '/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnRoute: typeof LearnRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  VocabRoute: typeof VocabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocab': {
      id: '/vocab'
      path: '/vocab'
      fullPath: '/vocab'
      preLoaderRoute: typeof VocabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/pinyin': {
      id: '/learn/pinyin'
      path: '/pinyin'
      fullPath: '/learn/pinyin'
      preLoaderRoute: typeof LearnPinyinRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/practice': {
      id: '/learn/practice'
      path: '/practice'
      fullPath: '/learn/practice'
      preLoaderRoute: typeof LearnPracticeRouteImport
      parentRoute: typeof LearnRoute
    }
  }
}

interface LearnRouteChildren {
  LearnPinyinRoute: typeof LearnPinyinRoute
  LearnPracticeRoute: typeof LearnPracticeRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnPinyinRoute: LearnPinyinRoute,
  LearnPracticeRoute: LearnPracticeRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnRoute: LearnRouteWithChildren,
  ProfileRoute: ProfileRoute,
  VocabRoute: VocabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
